# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Tabú"

KEYWORDS="*"

banpattern_tabs='/\t/{=;s//####/gp}'
banpattern_bandera='/\(bandera\)/{=;s//\U\1\E/gp}'
banpattern_links2='/\(links2\)/{=;s//\U\1\E/gp}'
banpattern_correr='/\([^[:alpha:]]\)\(correr\)/{=;s//\1\U\2\E/gp}'

exec_module() {
	local retVal=0

	OUTPUT_TEXT="Banned patterns found:"

	for p in ${!banpattern_*} ; do
		res=$(sed -n -e ${!p} ${DOC} | sed -e '/^[0-9]\+$/{N;s-\n[[:blank:]]*-\t-g}')
		if [[ -n ${res} ]] ; then
			retVal=2
			OUTPUT_TEXT="${OUTPUT_TEXT}

 - Using banned pattern '${p#banpattern_}' I spotted shait at:
--- 8< ---
${res}
--- 8< ---"
		fi
	done

	return ${retVal}
}
