# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Dynamic metadoc"
KEYWORDS="-* dynamic"

LEVEL="BASIC"

exec_module() {
	local LINE_LINK_TYPE TMP_LINK_ATTRIBUTE \
		LINK_ATTRIBUTE CORRECT_LINK

	# Get link_type line beggining with <dynamic
	LINE_LINK_TYPE=$(grep \<dynamic ${DOC})
	# Delete all before metadoc="
	TMP_LINK_ATTRIBUTE=${LINE_LINK_TYPE##*metadoc=\"}
	# Delete all after first "
	LINK_ATTRIBUTE=${TMP_LINK_ATTRIBUTE%%\"*}

	# The correct tag should be
	CORRECT_LINK=${WWW_DIR}"/metadoc.xml"

	if [[ ${CORRECT_LINK} != ${LINK_ATTRIBUTE} ]]; then
		# Path is not right
		# Building log message
		OUTPUT_TEXT="The attribute metadoc on ${LINE_LINK_TYPE} is
 wrong. Should point to the absolute metadoc path
 (metadoc=\"${CORRECT_LINK}\")"

		return 2
	else
		# Path is ok
		return 0
	fi
}
