# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Check language label"

KEYWORDS="guide"
LEVEL="BASIC"

exec_module() {
	${TRANSLATION} || return
	# Check the doc to find if lang attribute is set on guide label

	TMP_LANG=$(grep '<guide' /${DOC} | grep lang=\"${LANGUAGE}\")
	if [[ -z ${TMP_LANG} ]]; then
		OUTPUT_TEXT="Your guide link should use the attribute lang=\"${LANGUAGE}\""
		return 2
	else
		return 0
	fi
}
