# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Length of lines"
KEYWORDS="* -metadoc"

LEVEL="BASIC"

exec_module() {
	# Making exceptions using sed:
	# 1. <Header
	# 2. <comment> labels
	# 3. link= attributes
	# 4. Code lines using # <i>
	# 5. Code lines using $ <i>
	# 6. <pre caption= headers

	LONG_LINES=$(sed -n -e '
		/^<pre .*>/,/^<\/pre>/d
		/<!-- \$Header:/d
		/link=/d
		/^<title>/d
		/^.\{81,\}$/{=;p}
	' ${DOC} | sed -e '/^[0-9]\+$/{N;s-\n[[:blank:]]*-\t-g}')

	if [[ -z ${LONG_LINES} ]]; then
		return 0
	else
		OUTPUT_TEXT="${LONG_LINES}"
		return 1
	fi
}
