#!/bin/bash

# Repodoc Tool written by José Luis Rivero (yoswink@gentoo.org)
# Version 0.1_alpha
# Distributed under the terms of the GNU General Public License v2

MODULE_NAME="Length of lines"
KEYWORDS="* -metadoc"

LEVEL="BASIC"

exec_module() {
	# Making exceptions using sed:
	# 1. <Header
	# 2. <comment> labels
	# 3. link= attributes
	# 4. Code lines using # <i>
	# 5. Code lines using $ <i>
	# 6. <pre caption= headers

	LONG_LINES=$(sed -n -e '
		/^<pre .*>/,/^<\/pre>/d
		/<!-- \$Header:/d
		/link=/d
		/^<title>/d
		/^.\{81,\}$/{=;p}
	' ${DOC})

	if [[ -z ${LONG_LINES} ]]; then
		OUTPUT_RESULT="ok"
	else
		OUTPUT_RESULT="warning"
		OUTPUT_TEXT="${LONG_LINES}"
	fi
}
