# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

needlib xpath.sh

MODULE_NAME="Links"
KEYWORDS="*"

LEVEL="BASIC"

exec_module() {
	local external anchor_expr anchor \
		found anchor_found linked LINKS \
		out retVal=0

	# We have three types of links
	# 1. gentoo own links : /doc or /proj   ( internal - check          )
	# 2. GuideXml thingies : #doc_*         ( internal - check          )
	# 3. anchors : #links                   ( internal - check          )
	# 4. outside links : www and http...    ( external - cannot check   )
	# 5. Odd uris : irc mailto nx ssh ...   ( external - will not check )

	LINKS=$(doxpath ${DOC} '//uri/@link' '//uri[not(@link)]/text()')

	for link in ${LINKS} ; do
		anchor=${link##*#}
		anchor_expr='count(//*[@id="'${anchor}'"])'
		anchor_found=true
		found=false

		case ${link} in
			http?://*|ftp?://*|www.*)
				# Cannot check this links right now
				external=true
			;;
			\#doc_*)
				# This is a GuideXML internal link
				external=false

				[[ -z $(doxpath ${DOC} $(anchor2xpath ${link})) ]] \
					&& found=false || found=true
			;;
			\#*)
				# Anchor, internal, check it
				external=false
				[[ $(doxpath ${DOC} ${anchor_expr}) = 1 ]] && found=true || found=false
			;;
			/doc/*|/proj/*)
				# Gentoo link, internal, check it
				external=false
				found=false
				linked=${CVS_ROOT}/${link%%#*}

				# Does the file/directory exist ?
				[[ -e ${linked%%\?*} ]] && found=true

				# If we were given an anchor, check it
				case ${found},${anchor} in
					true,${link}) ;; # Skip if no anchor given
					true,doc_*)
						[[ -z $(doxpath ${linked%%\?*} $(anchor2xpath \#${anchor})) ]] \
							&& anchor_found=false || anchor_found=true
					;;
					true,*)
						[[ $(doxpath ${linked%%\?*} ${anchor_expr}) = 1 ]] \
							&& anchor_found=true || anchor_found=false
					;;
				esac

				${found} && ${anchor_found} || { [[ ${retVal} < 2 ]] && retVal=1 ;}
			;;
			*)
				# What on earth are you linking to?
				external=true
			;;
		esac

		${found} || ${external} || retVal=2

		case ${external},${found},${anchor_found} in
			true,*,*) ;;   # Skip external links
			false,false,*) out="${out},,,Link not found - ${link}" ;;
			false,true,false) out="${out},,,Anchor '${anchor}' not found in '${linked%%\?*}'" ;;
		esac
	done

	# A bit hacky, but works fine
	OUTPUT_TEXT=$(echo -e "${out//,,,/\n}")

	return ${retVal}
}
