# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Path"
KEYWORDS="* -metadoc -sections -inserts -mainpage"

LEVEL="BASIC"

exec_module() {
	local LINK_TYPE LINE_LINK_TYPE TMP_LINK_ATTRIBUTE \
		LINK_ATTRIBUTE CORRECT_LINK LINK_TAG

	# Select the line to extract link attribute
	LINK_TYPE="<${DOC_TYPE}"
	# Get link_type line
	LINE_LINK_TYPE=$(grep ${LINK_TYPE} ${DOC})
	# Delete all before link="
	TMP_LINK_ATTRIBUTE=${LINE_LINK_TYPE##*link=\"}
	# Delete all after first "
	LINK_ATTRIBUTE=${TMP_LINK_ATTRIBUTE%%\"*}

	# The correct tag should be
	CORRECT_LINK=${WWW_DIR}"/"${DOC_NAME}

	if [[ ${CORRECT_LINK} != ${LINK_ATTRIBUTE} ]]; then
		# Path is not right
		# Building log message
		LINK_TAG=$(grep "${LINK_TYPE}" ${DOC})
		OUTPUT_TEXT="The attribute link on ${LINK_TAG} is wrong. Should point to the absolute path (link=\"${CORRECT_LINK}\")"
		return 2
	else
		# Path is ok
		return 0
	fi
}
