# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Path"
KEYWORDS="* -metadoc -sections -inserts -mainpage -dynamic"

LEVEL="BASIC"


exec_module() {
	local LINK_ATTRIBUTE CORRECT_LINK DOCTYPE_TAG

	# Extract link attribute from $doc_type xml tag
	LINK_ATTRIBUTE=$(get-xmlattribute "${DOC_TYPE}" "link" "${DOC}")

	# The correct tag should be
	CORRECT_LINK=${WWW_DIR}"/"${DOC_NAME}

	if [[ ${CORRECT_LINK} != ${LINK_ATTRIBUTE} ]]; then
		# Path is not right
		# Building log message
		DOCTYPE_TAG=$(get-xmltag "${DOC_TYPE}" "${DOC}")
		OUTPUT_TEXT="The attribute link on ${LINK_TAG} is wrong. Should point to the absolute path (link=\"${CORRECT_LINK}\")"
		return 2
	else
		# Path is ok
		return 0
	fi
}
