#!/bin/bash

# Repodoc Tool written by José Luis Rivero (yoswink@gentoo.org)
# Version 0.1_alpha
# Distributed under the terms of the GNU General Public License v2

MODULE_NAME="Check version and date sync"
KEYWORDS="* -metadoc -inserts"

LEVEL="BASIC"

exec_module() {
	# Only check translations
	${TRANSLATION} || return

	# Extract version info about original doc
	ORIGINAL_VERSION=$(sed -n -e '/<version>.*<\/version>/p' ${ORIGINAL_DOC})
	
	# Extract version info about doc analysed
	DOC_VERSION=$(sed -n -e '/<version>.*<\/version>/p' ${DOC})

	#Extract date from original doc
	ORIGINAL_DATE=$(sed -n -e '/<date>.*<\/date>/p' ${ORIGINAL_DOC})
	
	#Extract date from doc analysed
	DOC_DATE=$(sed -n -e '/<date>.*<\/date>/p' ${DOC})

	if [[ ${ORIGINAL_VERSION} == ${DOC_VERSION} ]]; then
		# Dates are synced, still to check dates
		if [[ ${ORIGINAL_DATE} == ${DOC_DATE} ]]; then
			# Version and date are synced
			OUTPUT_TEXT=""
			return 0
		else
			# Date is not synced
			OUTPUT_TEXT="
Original english doc and the translation have different
date tags. Since version is the same, probably you should
update the date too."
			return 2
		fi
	else
		# Version is not synced
		OUTPUT_TEXT="
Original english doc and the translation have different
version tags. The doc could be out of date or you forgot to make cvs up
on english cvs dir."
		return 2
	fi
}
