# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Up2date"
KEYWORDS="* -metadoc -inserts -dynamic"
NEED_TRANSLATION=true

LEVEL="BASIC"

exec_module() {
	local ORIGINAL_VERSION DOC_VERSION ORIGINAL_DATE DOC_DATE

	# Extract version info about original doc
	ORIGINAL_VERSION=$(doxpath ${ORIGINAL_DOC} "/${DOC_TYPE}/version/text()")
	
	# Extract version info about doc analysed
	DOC_VERSION=$(doxpath ${DOC} "/${DOC_TYPE}/version/text()")

	#Extract date from original doc
	ORIGINAL_DATE=$(doxpath ${ORIGINAL_DOC} "/${DOC_TYPE}/date/text()")
	
	#Extract date from doc analysed
	DOC_DATE=$(doxpath ${DOC} "/${DOC_TYPE}/date/text()")

	if [[ ${ORIGINAL_VERSION} == ${DOC_VERSION} ]]; then
		# Dates are synced, still to check dates
		if [[ ${ORIGINAL_DATE} == ${DOC_DATE} ]]; then
			# Version and date are synced
			OUTPUT_TEXT=""
			return 0
		else
			# Date is not synced
			OUTPUT_TEXT="
Original english doc and the translation have different
date tags. Since version is the same, probably you should
update the date too."
			return 2
		fi
	else
		# Version is not synced
		OUTPUT_TEXT="
Original english doc and the translation have different
version tags. The doc could be out of date or you forgot to make cvs up
on english cvs dir."
		return 2
	fi
}
