# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Check version sync"
KEYWORDS="-* metadoc inserts"

LEVEL="BASIC"

exec_module() {
	local ORIGINAL_VERSION DOC_VERSION

	# Only procces translations
	${TRANSLATION} || return

	# Extract version info about original doc
	ORIGINAL_VERSION=$(sed -n -e '/<version>.*<\/version>/p' ${ORIGINAL_DOC})
	# Extract version info about doc analysed
	DOC_VERSION=$(sed -n -e '/<version>.*<\/version>/p' ${DOC})

	[[ ${ORIGINAL_VERSION} = ${DOC_VERSION} ]] && return 0

	OUTPUT_TEXT="
Original english doc and the translation have different
versions. The doc could be out of date or you forgot to make cvs up
on english dir."

	return 2
}
