#!/bin/bash

# Repodoc Tool written by José Luis Rivero (yoswink@gentoo.org)
# Distributed under the terms of the GNU General Public License v2

MODULE_NAME="Check xml health"
KEYWORDS="*"

LEVEL="BASIC"

exec_module() {
	VALIDATOR_COMMAND="xmllint --valid --noout"

	TMP_VALID=$(${VALIDATOR_COMMAND} ${DOC} 2>&1)

	if [[ -z ${TMP_VALID} ]]; then
		return 0
	else
		OUTPUT_TEXT=${TMP_VALID}
		return 2
	fi
}
