# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

needlib xml.sh

MODULE_NAME="Dynamic metadoc"
KEYWORDS="-* dynamic"

LEVEL="BASIC"

exec_module() {
	local LINK_ATTRIBUTE CORRECT_LINK

	# Extract attribute metadoc from <dynamic tag
	LINK_ATTRIBUTE=$(get-xmlattribute "dynamic" "metadoc" "${DOC}")

	# The correct tag should be
	CORRECT_LINK=${WWW_DIR}"/metadoc.xml"

	if [[ ${CORRECT_LINK} != ${LINK_ATTRIBUTE} ]] ; then
		# Path is not right
		# Building log message
		OUTPUT_TEXT="The attribute metadoc on ${LINK_ATTRIBUTE} is
 wrong. Should point to the absolute metadoc path
 (metadoc=\"${CORRECT_LINK}\")"

		return 2
	else
		# Path is ok
		return 0
	fi
}
