# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Header"

KEYWORDS="*"
LEVEL="BASIC"


# Check the doc to find if lang attribute is set on guide label
exec_module() {
	if ! grep '<!-- $Header:' ${DOC} >/dev/null 2>/dev/null ; then
		OUTPUT_TEXT="You should add \"<!-- \$Header:\$ -->\" a line after the xml version tag."
		return 1
	else
		return 0
	fi
}
