# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Header"

KEYWORDS="*"
LEVEL="BASIC"


# Check the doc to find if lang attribute is set on guide label
exec_module() {
	local TMP_HEADER=$(grep '<!-- $Header:' ${DOC})

	if [[ -z ${TMP_HEADER} ]] ; then
		OUTPUT_TEXT="You should add \"<!-- \$Header:\$ -->\" a line after the xml version tag."
		return 1
	else
		return 0
	fi
}
