# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

needlib xml.sh

MODULE_NAME="Lang"

KEYWORDS="guide"
LEVEL="BASIC"
NEED_TRANSLATION=true

exec_module() {
	local TMP_LANG

	# Check the doc to find if lang attribute is set on guide label
	if [[ -z $(get-xmlattribute guide lang "${DOC}") ]]; then
		OUTPUT_TEXT="Your guide link should use the attribute lang=\"${LANGUAGE}\""
		return 2
	else
		return 0
	fi
}
