# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

MODULE_NAME="Length"
KEYWORDS="* -metadoc"

LEVEL="BASIC"

exec_module() {
	local LONG_LINES

	# Making exceptions using sed:
	# 1. <Header
	# 2. <comment> labels
	# 3. link= attributes
	# 4. Code lines using # <i>
	# 5. Code lines using $ <i>
	# 6. <pre caption= headers

	LONG_LINES=$(sed -n -e '
		/^<pre .*>/,/^<\/pre>/d
		/<!-- \$Header:/d
		/^link="[^"]*"$/d
		/^<title>/d
		/^<guide .*>$/d
		/^[[:blank:]]*<uri>[^<]*<\/uri>$/d
		/^.\{81,\}$/{=;p}
	' ${DOC} | sed -f "${LIB_DIR}/massagelinenumbers.sed")

	if [[ -z ${LONG_LINES} ]] ; then
		return 0
	else
		OUTPUT_TEXT="${LONG_LINES}"
		return 1
	fi
}
