# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

needlib xpath.sh docpath.sh

KEYWORDS="metadoc"
NEED_TRANSLATION=true

LEVEL="BASIC"

exec_module() {
	local link flink LINKS langlink \
		out retVal=0

        # Call to doxpath
	LINKS=$(doxpath "${DOC}" "/metadoc/files/file/text()")

	# Check links
	for link in ${LINKS} ; do
		# Building full link needed by "-f" and localize-path
		flink="${CVS_ROOT}${link}"

		# 1. First Check. Does the link exist?
		if [[ ! -f ${flink} ]] ; then
			# Link doesn't exists
			retVal=2
			out="${out},,,The link: ${link} doesn't exists"'!'
		fi

		# 2. Second Check. Does the link point to the proper
		# translation?
		case ${link} in
			*/en/*)
				# Candidate language link
				langlink=$(localize-path "${flink}" "${LANGUAGE}")
				#echo $link $langlink
				# Does the langlink file/directory exist ?
				if [[ -e ${langlink} ]] ; then
					# Exists! give an error
					retVal=2
					out="${out},,,A doc translation for link: ${link} exists"'!'
				fi
		esac
	done

	# A bit hacky, but works fine
	OUTPUT_TEXT=$(echo -e "${out//,,,/\n}")

	return ${retVal}
}
