# Distributed under the terms of the GNU General Public License v2
# Copyright 2005-2006 The RepoDoc Team

needlib xml.sh

MODULE_NAME="Trans"
KEYWORDS="* -metadoc -inserts"
NEED_TRANSLATION=true

LEVEL="BASIC"

exec_module() {
	local orig="${REPO_TMP_DIR}/original.xml.$$" \
		trans="${REPO_TMP_DIR}/translation.xml.$$"

	get-xmltree "${ORIGINAL_DOC}" > "${orig}"
	get-xmltree "${DOC}" > "${trans}"

	OUTPUT_TEXT=$(diff -Nut "${orig}" "${trans}")

	rm "${orig}" "${trans}"

	if [[ -z ${OUTPUT_TEXT} ]] ; then
		return 0
	else
		return 1
	fi
}
